package trie_2;

/**
 * DO NOT EDIT THIS FILE.
 */
    public interface TrieInterface<T> {
    /**
     * @param word  Word to be input in the Trie
     * @param value Associated value of the word
     * @return Success or failure
     */
    public boolean insert(String word, T value);

    /**
     * @param word Search for this word, Case-Sensitive
     * @return Returns the Trienode associated if the word is found else NULL
     */
    public Node<T> search(String word);

    
    public  boolean delete(String word);

    /**
     * Print the complete Trie
     */
       
}
